CREATE USER MGMT_DEV IDENTIFIED BY "${place-holder-dev}" QUOTA UNLIMITED ON DATA;
GRANT CONNECT, RESOURCE TO MGMT_DEV;
CREATE USER MGMT_PROD IDENTIFIED BY "${place-holder-prod}" QUOTA UNLIMITED ON DATA;
GRANT CONNECT, RESOURCE TO MGMT_PROD;
